import React, { createContext, useContext, useState, useEffect } from 'react';
import { saveDashboardConfigApi, type RecommendedKPI, type RecommendedChart } from '../lib/api';
import { useDataset } from './datasetStore';
import { useAuth } from './authStore';

export interface DashboardItem {
  id: string;
  type: 'kpi' | 'chart';
  kpiData?: RecommendedKPI;
  chartData?: RecommendedChart;
}

interface DashboardContextType {
  items: DashboardItem[];
  addItem: (item: DashboardItem) => void;
  removeItem: (id: string) => void;
  moveItemUp: (index: number) => void;
  moveItemDown: (index: number) => void;
  autoGenerateDashboard: (kpis: RecommendedKPI[], charts: RecommendedChart[]) => void;
  clearDashboard: () => void;
  isInDashboard: (id: string) => boolean;
  setDashboardItems: (items: DashboardItem[]) => void;
}

const DashboardContext = createContext<DashboardContextType | undefined>(undefined);

export const DashboardProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { dataset } = useDataset();
  const { user } = useAuth();
  const fileId = dataset?.file_id;
  const userId = user?.id;

  const getStorageKey = (fid?: string, uId?: string) =>
    uId
      ? `insightiq_u_${uId}_dashboard_${fid || 'default'}`
      : `insightiq_guest_dashboard_${fid || 'default'}`;

  const storageKey = getStorageKey(fileId, userId);

  const parseSavedDashboardItems = (raw: string | null): DashboardItem[] => {
    if (!raw) return [];
    try {
      const parsed = JSON.parse(raw);
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  };

  const [items, setItems] = useState<DashboardItem[]>(() => {
    if (!fileId) return [];
    return parseSavedDashboardItems(localStorage.getItem(storageKey));
  });

  const safeItems = Array.isArray(items) ? items : [];

  // Reset state on logout
  useEffect(() => {
    const handleLogout = () => {
      setItems([]);
    };
    window.addEventListener('insightiq_logout', handleLogout);
    return () => {
      window.removeEventListener('insightiq_logout', handleLogout);
    };
  }, []);

  // Re-load when fileId or storageKey changes
  useEffect(() => {
    if (!fileId) {
      setItems([]);
      return;
    }
    setItems(parseSavedDashboardItems(localStorage.getItem(storageKey)));
  }, [fileId, storageKey]);

  // Sync to localStorage and backend if logged in
  const saveItems = (newItems: DashboardItem[]) => {
    const safeNewItems = Array.isArray(newItems) ? newItems : [];
    setItems(safeNewItems);
    if (fileId) {
      try {
        localStorage.setItem(storageKey, JSON.stringify(safeNewItems));
      } catch (err) {
        console.error('Failed to save dashboard to localStorage:', err);
      }
      if (user) {
        saveDashboardConfigApi(fileId, safeNewItems).catch((err) => {
          console.warn('Failed to save dashboard config to backend:', err);
        });
      }
    }
  };

  const setDashboardItems = (newItems: DashboardItem[]) => {
    saveItems(newItems);
  };

  const addItem = (item: DashboardItem) => {
    if (safeItems.some((i) => i.id === item.id)) return;
    saveItems([...safeItems, item]);
  };

  const removeItem = (id: string) => {
    saveItems(safeItems.filter((i) => i.id !== id));
  };

  const moveItemUp = (index: number) => {
    if (index <= 0) return;
    const newItems = [...safeItems];
    const temp = newItems[index - 1];
    newItems[index - 1] = newItems[index];
    newItems[index] = temp;
    saveItems(newItems);
  };

  const moveItemDown = (index: number) => {
    if (index >= safeItems.length - 1) return;
    const newItems = [...safeItems];
    const temp = newItems[index + 1];
    newItems[index + 1] = newItems[index];
    newItems[index] = temp;
    saveItems(newItems);
  };

  const autoGenerateDashboard = (kpis: RecommendedKPI[], charts: RecommendedChart[]) => {
    const safeKpis = Array.isArray(kpis) ? kpis : [];
    const safeCharts = Array.isArray(charts) ? charts : [];

    const selectedKpis = safeKpis.slice(0, 4).map((kpi) => ({
      id: `kpi_${kpi.kpi_name}`,
      type: 'kpi' as const,
      kpiData: kpi,
    }));

    const selectedCharts = safeCharts.slice(0, 4).map((chart) => ({
      id: `chart_${chart.title}`,
      type: 'chart' as const,
      chartData: chart,
    }));

    saveItems([...selectedKpis, ...selectedCharts]);
  };

  const clearDashboard = () => {
    saveItems([]);
  };

  const isInDashboard = (id: string) => {
    return safeItems.some((i) => i.id === id);
  };

  return (
    <DashboardContext.Provider
      value={{
        items: safeItems,
        addItem,
        removeItem,
        moveItemUp,
        moveItemDown,
        autoGenerateDashboard,
        clearDashboard,
        isInDashboard,
        setDashboardItems,
      }}
    >
      {children}
    </DashboardContext.Provider>
  );
};

export const useDashboard = () => {
  const context = useContext(DashboardContext);
  if (!context) {
    throw new Error('useDashboard must be used within a DashboardProvider');
  }
  return context;
};
