import React, { useState } from 'react';
import {
  ArrowDown,
  ArrowUp,
  BarChart3,
  Gauge,
  LayoutDashboard,
  Loader2,
  Plus,
  Sparkles,
  Trash2,
  X
} from 'lucide-react';
import { useDataset } from '../../store/datasetStore';
import { useDashboard } from '../../store/dashboardStore';
import { fetchDatasetKPIs, fetchDatasetCharts } from '../../lib/api';
import { KPICard } from './KPICard';
import { RenderedChartCard } from './RenderedChartCard';

interface DashboardBuilderProps {
  onNavigateTab?: (tab: 'KPIs' | 'Visualizations') => void;
}

export const DashboardBuilder: React.FC<DashboardBuilderProps> = ({ onNavigateTab }) => {
  const { dataset, clearDataset } = useDataset();
  const { items, removeItem, moveItemUp, moveItemDown, autoGenerateDashboard, clearDashboard } = useDashboard();
  const [generating, setGenerating] = useState<boolean>(false);

  const handleGenerateDefaultDashboard = async () => {
    if (!dataset?.file_id) return;
    setGenerating(true);
    try {
      const [kpiRes, chartRes] = await Promise.all([
        fetchDatasetKPIs(dataset.file_id),
        fetchDatasetCharts(dataset.file_id),
      ]);
      autoGenerateDashboard(kpiRes.kpis || [], chartRes.charts || []);
    } catch (err) {
      console.error('Failed to auto-generate dashboard:', err);
    } finally {
      setGenerating(false);
    }
  };

  if (!dataset) {
    return (
      <div className="w-full max-w-4xl mx-auto flex flex-col items-center justify-center min-h-[65vh] text-center p-8 rounded-2xl border border-dashed border-hairline bg-surface-soft/40 space-y-4">
        <div className="w-16 h-16 rounded-2xl bg-primary-light text-primary flex items-center justify-center text-3xl font-bold shadow-xs">
          <LayoutDashboard className="w-8 h-8" />
        </div>
        <div className="space-y-1">
          <h2 className="text-title-lg text-ink font-bold">No Dataset Loaded</h2>
          <p className="text-body-md text-muted max-w-md mx-auto leading-relaxed">
            Upload a dataset to build custom executive dashboards combining key metric cards and interactive charts.
          </p>
        </div>
        <div className="pt-2">
          <button onClick={clearDataset} className="btn-primary gap-2">
            <Plus className="w-4 h-4" />
            <span>Upload a Dataset</span>
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="w-full max-w-6xl mx-auto space-y-6 pb-12">
      {/* Header Banner */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-6 rounded-2xl border border-hairline bg-surface-card shadow-xs">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl bg-primary-light text-primary flex items-center justify-center shrink-0">
            <LayoutDashboard className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-title-md text-ink font-bold">Executive Dashboard</h2>
              <span className="px-2.5 py-0.5 text-xs font-semibold bg-primary-light text-primary rounded-full border border-primary/20">
                {items.length} Elements
              </span>
            </div>
            <p className="text-caption text-muted">
              Composed metric cards and interactive visualizations for {dataset.filename}
            </p>
          </div>
        </div>

        {/* Header Action Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleGenerateDefaultDashboard}
            disabled={generating}
            className="btn-primary py-2 px-3.5 text-xs gap-1.5"
            title="Auto-populate dashboard with top metrics and charts"
          >
            {generating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4 text-amber-300" />
            )}
            <span>Generate Dashboard</span>
          </button>

          {items.length > 0 && (
            <button
              onClick={clearDashboard}
              className="btn-ghost py-2 px-3 text-xs gap-1.5 text-error hover:bg-error-bg/20"
              title="Clear all items from dashboard"
            >
              <Trash2 className="w-4 h-4" />
              <span>Clear</span>
            </button>
          )}
        </div>
      </div>

      {/* Empty State */}
      {items.length === 0 ? (
        <div className="p-8 md:p-12 rounded-2xl border border-dashed border-hairline bg-surface-card text-center space-y-4 max-w-2xl mx-auto my-8">
          <div className="w-14 h-14 rounded-2xl bg-surface-soft text-muted flex items-center justify-center mx-auto">
            <LayoutDashboard className="w-7 h-7 text-primary" />
          </div>
          <div className="space-y-1">
            <h3 className="text-title-md text-ink font-bold">Your Dashboard is Empty</h3>
            <p className="text-body-sm text-muted max-w-md mx-auto">
              Add KPIs from the KPI Studio or charts from the Visualization Studio, or generate an automated dashboard.
            </p>
          </div>

          <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
            <button
              onClick={handleGenerateDefaultDashboard}
              disabled={generating}
              className="btn-primary gap-2"
            >
              {generating ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Sparkles className="w-4 h-4 text-amber-300" />
              )}
              <span>Auto-Generate Dashboard</span>
            </button>

            {onNavigateTab && (
              <>
                <button
                  onClick={() => onNavigateTab('KPIs')}
                  className="btn-secondary gap-1.5"
                >
                  <Gauge className="w-4 h-4 text-primary" />
                  <span>Explore KPIs</span>
                </button>
                <button
                  onClick={() => onNavigateTab('Visualizations')}
                  className="btn-secondary gap-1.5"
                >
                  <BarChart3 className="w-4 h-4 text-emerald-500" />
                  <span>Explore Visualizations</span>
                </button>
              </>
            )}
          </div>
        </div>
      ) : (
        /* Dashboard Items Grid */
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start">
          {items.map((item, index) => {
            const isFirst = index === 0;
            const isLast = index === items.length - 1;
            const isChart = item.type === 'chart';

            return (
              <div
                key={item.id}
                className={`relative group transition-all ${
                  isChart ? 'lg:col-span-2' : 'col-span-1'
                }`}
              >
                {/* Control Action Toolbar Bar */}
                <div className="absolute top-3 right-3 z-20 flex items-center gap-1 bg-surface-card/90 backdrop-blur-sm p-1 rounded-xl border border-hairline shadow-xs opacity-90 group-hover:opacity-100 transition-opacity">
                  <button
                    onClick={() => moveItemUp(index)}
                    disabled={isFirst}
                    className="p-1 rounded-lg hover:bg-surface-soft text-muted hover:text-ink disabled:opacity-30 disabled:hover:bg-transparent"
                    title="Move Item Up"
                  >
                    <ArrowUp className="w-3.5 h-3.5" />
                  </button>
                  <button
                    onClick={() => moveItemDown(index)}
                    disabled={isLast}
                    className="p-1 rounded-lg hover:bg-surface-soft text-muted hover:text-ink disabled:opacity-30 disabled:hover:bg-transparent"
                    title="Move Item Down"
                  >
                    <ArrowDown className="w-3.5 h-3.5" />
                  </button>
                  <button
                    onClick={() => removeItem(item.id)}
                    className="p-1 rounded-lg hover:bg-error-bg text-muted hover:text-error transition-colors"
                    title="Remove from Dashboard"
                  >
                    <X className="w-3.5 h-3.5" />
                  </button>
                </div>

                {/* Render Item Component */}
                {item.type === 'kpi' && item.kpiData && (
                  <KPICard kpi={item.kpiData} />
                )}

                {item.type === 'chart' && item.chartData && (
                  <RenderedChartCard
                    chartConfig={item.chartData}
                    fileId={dataset.file_id}
                  />
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
